services:
  # HTML
  frontend-app:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    
    # コンテナ名・ホスト名
    container_name: frontend_app
    hostname: frontend_app
    
    # デフォルトのポートを指定
    ports:
      - "8080:80"

    # --- ↓↓↓ ここから追加 ↓↓↓ ---
    volumes:
      - ./frontend/pages:/usr/share/nginx/html
    depends_on:
      - backend-app
    # --- ↑↑↑ ここまで追加 ↑↑↑ ---

  # Flask
  backend-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile

    # コンテナ名・ホスト名
    container_name: backend_app
    hostname: backend_app

  # python
  dev-container:
    build:
      context: .
      dockerfile: ./dev/Dockerfile

    # コンテナ名・ホスト名
    container_name: dev_container
    hostname: dev_container

    # --- ↓↓↓ ここから追加 ↓↓↓ ---
    volumes:
      # 注意: パスは実際のフォルダ構造に合わせてください
      # この ./ は docker-compose.yml があるディレクトリを指します。
      # : の右側はコンテナ内のマウント先パスで、workspaceFolder と合わせます。
      - ../.ssh:/home/vscode/.ssh # ホストのSSHキーをコンテナのvscodeユーザーの.sshへ
      - ../.gitconfig:/home/vscode/.gitconfig # ホストのGit設定をコンテナのvscodeユーザーのホームへ
      - ./:/src # docker-compose.ymlがあるディレクトリ全体をコンテナの/srcへ
    
    depends_on:
      - backend-app
    # --- ↑↑↑ ここまで追加 ↑↑↑ ---
